CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_name VARCHAR(100) NOT NULL,
    user_last_name VARCHAR(100) NOT NULL,
    type_access VARCHAR(50),
    CONSTRAINT PK_USER PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS cars (
    car_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    number_car INTEGER NOT NULL,
    vin_car VARCHAR(100) NOT NULL,
    year_release_car INTEGER NOT NULL,
    type_car VARCHAR(50),
    type_rent VARCHAR(50),
    CONSTRAINT PK_NUMBER_CAR PRIMARY KEY (number_car)
);

CREATE TABLE IF NOT EXISTS drivers (
    driver_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    driver_name VARCHAR(100) NOT NULL,
    driver_last_name VARCHAR(100) NOT NULL,
    number_driver_license INTEGER NOT NULL,
    driving_experience INTEGER NOT NULL,
    CONSTRAINT PK_NUMBER_DRIVER_LICENSE PRIMARY KEY (driver_id),
    CONSTRAINT FK_DRIVER_FOR_CAR FOREIGN KEY (number_driver_license)
        REFERENCES cars (number_car)
);